openapi: 3.0.1
info:
  title: STD21033
  description: Hello word
  version: 1.0.0
servers:
- url: https://std21033.com
tags:
- name: Students
- name: Courses
paths:
  /Students:
    get:
      tags:
      - Students
      summary: Get all students
      description: Get all students with details
      operationId: findPetsByStatus
      parameters:
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: page_size
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Students'
        400:
          description: Bad request
      security:
      - petstore_auth:
        - write:pets
        - read:pets
  /Student:
    post:
      tags:
      - Students
      summary: Create new students
      description: Create new students from an array
      operationId: addPet
      requestBody:
        description: Students to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudents'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateStudents'
        required: true
      responses:
        400:
          description: Bad request
      security:
      - petstore_auth:
        - write:pets
        - read:pets
components:
  schemas:
    CreateStudents:
      type: object
      properties:
        name:
          type: string
      xml:
        name: CreateStudents
    Students:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Students
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets